
name: Chat Notify

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      message:
        required: true
        type: string
      problem:
        required: true
        type: boolean
      urlChatWebHooks:
        required: true
        type: string

jobs:
  send-message:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "appName:" ${{ inputs.appName }}
        echo "message:" ${{ inputs.message }}
        echo "problem:" ${{ inputs.problem }}
        echo "urlChatWebHooks:" ${{ inputs.urlChatWebHooks }}
        
    - name: Write Message Content
      id: write-message-content
      run: |
        MESSAGE_CONTENT=${{ inputs.message }}
        echo "MESSAGE=$MESSAGE_CONTENT" >> $GITHUB_ENV
        echo ::set-output name=message::$NEW_VERSION
        
    - name: Notify 
      if: inputs.problem == false
      run: |
        curl --location --request POST '${{ inputs.urlChatWebHooks }}' \
        -H "Content-type: application/json; charset=utf-8" \
        -d "{\"text\":\"*${{ inputs.appName }}:* ${{needs.write-message-content.outputs.message}}\"}"        
