
name: Chat Notify Deploy

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      commit:
        required: true
        type: boolean
      problem:
        required: true
        type: boolean
      urlChatWebHooks:
        required: true
        type: string

jobs:
  send-message:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "repository:" ${{ inputs.repository }}
        echo "commit:" ${{ inputs.commit }}
        echo "problem:" ${{ inputs.problem }}
        echo "urlChatWebHooks:" ${{ inputs.urlChatWebHooks }}

    - name: Notify Problem
      if: inputs.problem == true
      run: |
        curl --location --request POST '${{ inputs.urlChatWebHooks }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "cardsV2": [
              {
                "cardId": "unique-card-id",
                "card": {
                  "header": {
                    "title": "GitHub Actions",
                    "subtitle": "VR Software",
                    "imageUrl": "https://storage.googleapis.com/imagem-aplicativos/bot/bot-github-problem.png",
                    "imageType": "CIRCLE",
                    "imageAltText": "GitHub Actions - VR Software"
                  },
                  "sections": [
                    {
                      "header": "${{ inputs.repository }}",
                      "collapsible": false,
                      "widgets": [
                        {
                          "decoratedText": {
                            "startIcon": {
                              "knownIcon": "EMAIL"
                            },
                            "text": "Algo deu errado ao lançar uma nova versão do ${{ inputs.repository }}"
                          }
                        },
                        {
                          "buttonList": {
                            "buttons": [
                              {
                                "text": "Repository",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/vrsoftbr/${{ inputs.repository }}"
                                  }
                                }
                              },
                              {
                                "text": "Actions",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/vrsoftbr/${{ inputs.repository }}/actions"
                                  }
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }'

    - name: Notify Sucess
      if: inputs.problem == false && inputs.commit == true
      run: |
        curl --location --request POST '${{ inputs.urlChatWebHooks }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "cardsV2": [
              {
                "cardId": "unique-card-id",
                "card": {
                  "header": {
                    "title": "GitHub Actions",
                    "subtitle": "VR Software",
                    "imageUrl": "https://storage.googleapis.com/imagem-aplicativos/bot/bot-github.png",
                    "imageType": "CIRCLE",
                    "imageAltText": "GitHub Actions - VR Software"
                  },
                  "sections": [
                    {
                      "header": "${{ inputs.repository }}",
                      "collapsible": false,
                      "widgets": [
                        {
                          "decoratedText": {
                            "startIcon": {
                              "knownIcon": "EMAIL"
                            },
                            "text": "Uma nova versão do ${{ inputs.repository }} está disponível"
                          }
                        },
                        {
                          "buttonList": {
                            "buttons": [
                              {
                                "text": "Repository",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/vrsoftbr/${{ inputs.repository }}"
                                  }
                                }
                              },
                              {
                                "text": "Releases",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/vrsoftbr/${{ inputs.repository }}/releases"
                                  }
                                }
                              },
                              {
                                "text": "Packages",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/orgs/vrsoftbr/packages?repo_name=${{ inputs.repository }}"
                                  }
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }'

    - name: Notify Unnecessary
      if: inputs.problem == false && inputs.commit == false
      run: |
        curl --location --request POST '${{ inputs.urlChatWebHooks }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "cardsV2": [
              {
                "cardId": "unique-card-id",
                "card": {
                  "header": {
                    "title": "GitHub Actions",
                    "subtitle": "VR Software",
                    "imageUrl": "https://storage.googleapis.com/imagem-aplicativos/bot/bot-github-warning.png",
                    "imageType": "CIRCLE",
                    "imageAltText": "GitHub Actions - VR Software"
                  },
                  "sections": [
                    {
                      "header": "${{ inputs.repository }}",
                      "collapsible": false,
                      "widgets": [
                        {
                          "decoratedText": {
                            "startIcon": {
                              "knownIcon": "EMAIL"
                            },
                            "text": "Nenhum \`commit\` desde o último Release/Tag no ${{ inputs.repository }}"
                          }
                        },
                        {
                          "buttonList": {
                            "buttons": [
                              {
                                "text": "Repository",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/vrsoftbr/${{ inputs.repository }}"
                                  }
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }'
