
name: Chat Notify

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      message:
        required: true
        type: string
      problem:
        required: true
        type: boolean
      urlChatWebHooks:
        required: true
        type: string

jobs:
  send-message:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "repository:" ${{ inputs.repository }}
        echo "message:" ${{ inputs.message }}
        echo "problem:" ${{ inputs.problem }}
        echo "urlChatWebHooks:" ${{ inputs.urlChatWebHooks }}
        
    - name: Notify
      if: inputs.problem == false
      run: |
        curl --location --request POST '${{ inputs.urlChatWebHooks }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "cardsV2": [
              {
                "cardId": "unique-card-id",
                "card": {
                  "header": {
                    "title": "GitHub Actions",
                    "subtitle": "VR Software",
                    "imageUrl": "https://storage.googleapis.com/imagem-aplicativos/bot/bot-github.png",
                    "imageType": "CIRCLE",
                    "imageAltText": "GitHub Actions - VR Software"
                  },
                  "sections": [
                    {
                      "header": "${{ inputs.repository }}",
                      "collapsible": false,
                      "widgets": [
                        {
                          "decoratedText": {
                            "startIcon": {
                              "knownIcon": "EMAIL"
                            },
                            "text": "${{ inputs.message }}"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }'
          
    - name: Notify Problem
      if: inputs.problem == true
      run: |
        curl --location --request POST '${{ inputs.urlChatWebHooks }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "cardsV2": [
              {
                "cardId": "unique-card-id",
                "card": {
                  "header": {
                    "title": "GitHub Actions",
                    "subtitle": "VR Software",
                    "imageUrl": "https://storage.googleapis.com/imagem-aplicativos/bot/bot-github-problem.png",
                    "imageType": "CIRCLE",
                    "imageAltText": "GitHub Actions - VR Software"
                  },
                  "sections": [
                    {
                      "header": "${{ inputs.repository }}",
                      "collapsible": false,
                      "widgets": [
                        {
                          "decoratedText": {
                            "startIcon": {
                              "knownIcon": "EMAIL"
                            },
                            "text": "${{ inputs.message }}"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }'          
