name: Checkout-Branch

on:
  workflow_call:
    inputs:
      main-project:
        description: 'Main project name that requires another project'
        required: true
        type: string

      child-project:
        description: 'Name of the child project to be checkout from the branch'
        required: true
        type: string

      main-project-branch-name:
        description: 'Branch name of the main project that will be used for checkout in the child project'
        required: true
        type: string
        

    secrets:
      VRPACKAGETOKEN:
        required: true

jobs:
  checkout-branch:
    name: checkout branch

    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ job.status}}
    
    steps:
      - name: Get Branch Name
        id: get_branch
        run: echo "##[set-output name=branch;]$(echo ${{ github.head_ref }})"

      - uses: actions/checkout@v3
        with:
          path: ${{ inputs.main-project }}
          token: ${{ secrets.VRPACKAGETOKEN }}  
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          path: ${{ inputs.child-project }}
          token: ${{ secrets.VRPACKAGETOKEN }}
          fetch-depth: 0

      - name: "Checkout ${{ inputs.child-project }} Branch"
        run: |
          cd ${{ inputs.child-project }}
          branchLocal=$(git ls-remote --heads origin ${{ steps.get_branch.outputs.branch }});
          if ! [ -z "$branchLocal" ]; then
                    branch=${{ steps.get_branch.outputs.branch }}
                    pwd
            else
                    cd ../${{ inputs.main-project }}
                    pwd
                    branch=$(git show-branch -a \
                    | grep '\*' \
                    | grep -v `git rev-parse --abbrev-ref HEAD` \
                    | head -n1 \
                    | sed 's/.*\[\(.*\)\].*/\1/' \
                    | sed 's/[\^~].*//') 
            fi
            echo $branch;
            cd ../${{ inputs.child-project }}
            git checkout $branch;

      - name: Caching projects 
        uses: actions/cache/save@v3
        with:
          path: |
            ~/ ${{inputs.main-project}}
            ~/ ${{ inputs.child-project }}
          key: ${{ runner.os }}-projects