name: Checkout-Branch

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Name of the project to be checkout from the branch'
        required: true
        type: string

    secrets:
      VRPACKAGETOKEN:
        required: true

jobs:
  checkout-branch:
    name: checkout branch

    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ job.status }}
    
    steps:
      - name: clone ${{ inputs.project-name }}
        uses: actions/checkout@v3
        with:
          repository: vrsoftbr/${{ inputs.project-name }}
          path: ${{ inputs.project-name }}
          token: ${{ secrets.VRPACKAGETOKEN }}
          fetch-depth: 0

      - name: "Checkout ${{ inputs.project-name }} Branch"
        run: |
          cd ${{ inputs.project-name }}
          branchLocal=$(git ls-remote --heads origin ${{ github.event.pull_request.head.ref }});
          if ! [ -z "$branchLocal" ]; then
                    branch=${{ github.event.pull_request.head.ref }}
            else
                    branch=${{ github.event.pull_request.base.ref }} 
            fi
            echo $branch;
            cd ../${{ inputs.project-name }}
            git checkout $branch;

      - name: Caching ${{ inputs.project-name }} 
        uses: actions/cache/save@v3
        with:
          path: |
            ${{ inputs.project-name }}
          key: ${{ inputs.project-name }}-${{ github.sha }}