name: Check Commit

on:
  workflow_call:
    secrets:
      VRPACKAGETOKEN:
        required: true
    inputs:
      byPass:
        description: 'Set a force return `true` to output `exist`, not affect in output `count`'
        required: false
        type: boolean
    outputs:
      count:
        description: 'Return he count of commits in main branch since last tag created'
        value: ${{ jobs.get-commit-count.outputs.count }}
      exist:
        description: 'Return if has commits in main branch since last tag created'
        value: ${{ jobs.get-commit-count.outputs.exist }}

jobs:
  get-commit-count:
    name: Get Commit Count
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.check_changes.outputs.commit_count }}
      exist: ${{ steps.check_changes.outputs.commit_exist }}
      status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VRPACKAGETOKEN }}
          fetch-depth: 0
          ref: main
          
      - name: Git Config
        run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" && git config --global user.name "${GITHUB_ACTOR}" 
      
      # - name: Check Commit Exist by pass
      #   id: check_commit_by_pass
      #   run: |
      #     VERIFY_COMMIT_EXIST=$([ inputs.byPass == true ] && echo "true" || ([ "$COMMIT_COUNT" == 0 ] && echo "false" || echo "true"))
      #     echo "ByPass: ${{ toJSON(inputs.byPass) }}"
      #     echo "Commit Count: $COMMIT_COUNT"
      #     echo "Verify commit exist: $VERIFY_COMMIT_EXIST"
      #     echo "verify_commit_exist=$VERIFY_COMMIT_EXIST" >> $GITHUB_OUTPUT
          # COMMIT_EXIST=${{steps.check_commit_by_pass.outputs.verify_commit_exist}}
      
      - name: Commits Since Last Tag
        id: check_changes
        run: |
          FIRST_TAG=$([ -z "$(git tag)" ] && echo "true" || echo "false")
          COMMIT_COUNT=$([ "$FIRST_TAG" == true ] && echo "999" || echo "$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)")
          COMMIT_EXIST=$([ ${{ toJSON(inputs.byPass) }} == true ] && echo "true" || ([ "$COMMIT_COUNT" == 0 ] && echo "false" || echo "true"))        
          echo "ByPass: ${{ toJSON(inputs.byPass) }}"
          echo "Commits since last tag: $COMMIT_COUNT"
          echo "Has commits since last tag: $COMMIT_EXIST"
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          echo "commit_exist=$COMMIT_EXIST" >> $GITHUB_OUTPUT
