name: Integration-test

on:
  workflow_call:
    inputs:
      task-name:
        description: 'Name of the gradle task to run'
        required: true
        type: string

      run-label:
        description: 'Name of the github runner'
        required: true
        type: string

    secrets:
      VRPACKAGETOKEN:
        required: true

jobs:
  integration-test:
    runs-on: ${{ inputs.run-label }}

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
 
      - name: executing ${{ inputs.task-name }}
        run: |
          cd VRCore && ./gradlew ${{ inputs.task-name }} -x VRNFe:integrationTest
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.VRPACKAGETOKEN }}

      - name: 'Integration Test report'
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ${{ inputs.task-name }}Report
          path: VRCore/build/reports/tests/${{ inputs.task-name }}
          retention-days: 2