name: Upgrade-database

on:
  workflow_call:
    inputs:
      run-label:
        description: 'Name of the github runner'
        required: true
        type: string

    secrets:
      VRPACKAGETOKEN:
        required: true

jobs:
  upgrade-database:
    runs-on: ["${{ inputs.run-label }}"]

    steps:
      - name: Run Docker Container from vrsoftbr/postgres
        run: |
          docker login ${{ secrets.VRDOCKERLOGIN }}
          docker run -P --name bancovr -p 5432:5432 -v ./db:/bkp -d vrsoftbr/postgres

      - name: Restore Backup
        run: |
          sleep 10
          docker exec bancovr restore_db

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          
      - name: Upgrade database
        run: |
          cd VRCore && ./gradlew atualizarTabelas  
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.VRPACKAGETOKEN }}